name = "voice-claude"
main = "src/index.js"
compatibility_date = "2024-12-05"

[observability]
enabled = true

[vars]
CLAUDE_MODEL = "claude-3-5-sonnet-20241022"

[[durable_objects.bindings]]
name = "CONVERSATION"
class_name = "VoiceClaudeConversation"

[[migrations]]
tag = "v1"
new_classes = ["VoiceClaudeConversation"]
