name = "voice-claude"
main = "src/index.js"
compatibility_date = "2024-12-05"

[observability]
enabled = true

[vars]
# https://docs.anthropic.com/en/docs/about-claude/models#model-names
CLAUDE_MODEL = "claude-3-5-sonnet-latest"

# https://www.twilio.com/docs/voice/twiml/say/text-speech#available-voices-and-languages
TWILIO_VOICE = "man"

[[durable_objects.bindings]]
name = "CONVERSATION"
class_name = "VoiceClaudeConversation"

[[migrations]]
tag = "v1"
new_classes = ["VoiceClaudeConversation"]
